# Generated by Django 4.1.1 on 2022-09-22 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FormulationAndLabManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('quantity', models.FloatField(null=True)),
                ('reorder_level', models.FloatField(null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('deficiency_request', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_quantity', models.PositiveIntegerField(null=True)),
                ('net_weight', models.PositiveIntegerField(choices=[('', 'Select weight in ml/g'), (15, 15), (100, 125), (125, 125), (250, 250)], null=True)),
                ('due_date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('', 'Select Status'), ('Scheduled', 'Scheduled'), ('On Hold', 'On Hold'), ('Completed', 'Completed')], default='Scheduled', max_length=200, null=True)),
                ('product_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FormulationAndLabManagement.products')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_requested', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('', 'Select Status'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Received', 'Received')], default='Pending', max_length=200, null=True)),
                ('rawmaterial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BatchProductionManagement.rawmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_quantity', models.PositiveIntegerField(null=True)),
                ('manufacture_date', models.DateField(null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('batch_details', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('', 'Select Status'), ('Ready', 'Ready'), ('Dispatched', 'Dispatched'), ('Received', 'Received')], default='Ready', max_length=200, null=True)),
                ('schedule_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BatchProductionManagement.scheduleproduction')),
            ],
        ),
    ]
