# Generated by Django 4.1.2 on 2022-11-03 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BatchProductionManagement', '0002_remove_rawmaterial_last_updated_request_last_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, null=True)),
                ('model', models.CharField(max_length=200, null=True)),
                ('year', models.PositiveIntegerField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('power_consumption', models.FloatField(null=True)),
                ('net_weight', models.FloatField(null=True)),
                ('dimensions', models.CharField(max_length=200, null=True)),
                ('date_purchased', models.DateField(null=True)),
                ('repair_duration', models.DurationField(null=True)),
                ('last_repair', models.DurationField(blank=True, null=True)),
                ('next_repair', models.DurationField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('', 'Select Condition'), ('Brand New', 'Brand New'), ('Need Repair', 'Need Repair'), ('Under maintenance', 'Under maintenance'), ('Not Functional', 'Not Functional')], default='Brand New', max_length=200, null=True)),
                ('image', models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='batch/')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterialHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('reorder_level', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateField(auto_now_add=True, null=True)),
                ('action', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_requested', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('', 'Select Status'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Received', 'Received')], default='Pending', max_length=200, null=True)),
                ('lastUpdated', models.DateField(auto_now_add=True, null=True)),
                ('action', models.CharField(blank=True, max_length=20, null=True)),
                ('rawmaterial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BatchProductionManagement.rawmaterial')),
            ],
        ),
    ]
