# Generated by Django 4.1.1 on 2022-09-23 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FormulationAndLabManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(blank=True, default='Mascara.jpg', null=True, upload_to='formulation/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='schedule_test_chemicals',
            name='chemical',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FormulationAndLabManagement.test_chemicals', unique=True),
        ),
        migrations.AlterField(
            model_name='test_chemicals',
            name='chemical_name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
