# Generated by Django 4.1.1 on 2022-09-27 07:58

import FormulationAndLabManagement.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FormulationAndLabManagement', '0002_alter_products_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulation',
            name='formulation_qty',
            field=models.FloatField(null=True, validators=[FormulationAndLabManagement.models.formulation.quantitity_validate]),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='formulation/'),
        ),
        migrations.AlterField(
            model_name='schedule_test_chemicals',
            name='chemical',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FormulationAndLabManagement.test_chemicals'),
        ),
    ]
