# Generated by Django 4.1.1 on 2022-09-22 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EmployeeManagement', '0001_initial'),
        ('BatchProductionManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemID', models.CharField(max_length=7, null=True)),
                ('itemName', models.CharField(max_length=30, null=True)),
                ('category', models.CharField(choices=[('', 'Select a Category'), ('Dock', 'Dock'), ('Conveyor', 'Conveyor'), ('Storage', 'Storage'), ('Lifting ', 'Lifting '), ('Packing', 'Packing')], max_length=30, null=True)),
                ('description', models.TextField(max_length=200, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('status', models.CharField(choices=[('', 'Select a Status'), ('Fair', 'Fair'), ('Good', 'Good'), ('Excellent', 'Excellent')], max_length=20, null=True)),
                ('lastMaintenanceDate', models.DateField(null=True)),
                ('nextMaintenanceDate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemID', models.CharField(max_length=7, null=True)),
                ('itemName', models.CharField(max_length=30, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
                ('action', models.CharField(max_length=20, null=True)),
                ('affect_table', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemID', models.CharField(max_length=7, null=True)),
                ('itemName', models.CharField(max_length=30, null=True)),
                ('category', models.CharField(choices=[('', 'Select a Category'), ('Primary ', 'Primary '), ('Secondary', 'Secondary'), ('Tertiary ', 'Tertiary ')], max_length=30, null=True)),
                ('description', models.TextField(max_length=200, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('reorderLevel', models.PositiveIntegerField(null=True)),
                ('materialType', models.CharField(choices=[('', 'Select a Type'), ('Plastic', 'Plastic'), ('Glass', 'Glass'), ('Steel', 'Steel'), ('Aluminum', 'Aluminum'), ('Paper and Paperboard', 'Paper and Paperboard'), ('Polythene', 'Polythene')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemID', models.CharField(max_length=7, null=True)),
                ('itemName', models.CharField(max_length=30, null=True)),
                ('category', models.CharField(max_length=30, null=True)),
                ('description', models.TextField(max_length=200, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('reorderLevel', models.PositiveIntegerField(null=True)),
                ('expireDate', models.DateField(null=True)),
                ('receivedDate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_ID', models.PositiveIntegerField(null=True)),
                ('req_from', models.CharField(choices=[('', 'Select a One Option'), ('BP Manager', 'BP Manager'), ('Supplier Manager', 'Supplier Manager')], max_length=30, null=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('itemName', models.CharField(max_length=30, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('due_Date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('', 'Select a Status'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Received', 'Received')], default='Pending', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workingArea', models.CharField(choices=[('', 'Select a Sector'), ('Loading Unloading', 'Loading Unloading'), ('Storage', 'Storage'), ('Order Preparation', 'Order Preparation'), ('Packing', 'Packing'), ('Dispatch and Outflow', 'Dispatch and Outflow'), ('Technical', 'Technical')], max_length=20, null=True)),
                ('availability', models.CharField(choices=[('', 'Select an Availability'), ('Free', 'Free'), ('On a Job', 'On a Job')], default='Free', max_length=10, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='EmployeeManagement.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('reorderLevel', models.IntegerField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BatchProductionManagement.batch')),
            ],
        ),
    ]
