# Generated by Django 4.1.2 on 2022-11-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarehouseManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouserequest',
            name='request_ID',
            field=models.PositiveIntegerField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='warehouserequest',
            name='type',
            field=models.CharField(choices=[('', 'Select a Type'), ('Raw Material', 'Raw Material'), ('Equipment', 'Equipment'), ('Packaging', 'Packaging'), ('Product', 'Product')], max_length=20, null=True),
        ),
    ]
