# Generated by Django 4.1.1 on 2022-09-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerAndSalesManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesproduct',
            name='category',
            field=models.CharField(choices=[('', 'Select a category..'), ('S', 'Skin Cosmetics'), ('F', 'Face Makeup'), ('N', 'Nail Cosmetics'), ('H', 'Hair Cosmetics'), ('O', 'Other Categories')], max_length=1, null=True),
        ),
    ]
