# Generated by Django 4.1.2 on 2022-11-02 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeManagement', '0002_alter_employees_status'),
        ('CustomerAndSalesManagement', '0002_alter_salesproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkorderrequest',
            name='province',
            field=models.CharField(choices=[('', 'Select a Province'), ('Western Province', 'Western Province'), ('Southern Province', 'Southern Province'), ('Eastern Province', 'Eastern Province'), ('Central Province', 'Central Province'), ('Northcentral Province', 'Northcentral Province'), ('Northern Province', 'Northern Province'), ('Northwest Province', 'Northwest Province'), ('Uwa Province', 'Uwa Province')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bulkorderrequest',
            name='request_status',
            field=models.CharField(default='Request Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesproduct',
            name='production_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salestask',
            name='sales_team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='CustomerAndSalesManagement.salesteam'),
        ),
        migrations.AlterField(
            model_name='salesteammembers',
            name='sales_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CustomerAndSalesManagement.salesteam'),
        ),
        migrations.AlterField(
            model_name='salesteammembers',
            name='team_member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='EmployeeManagement.employees'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(choices=[('', 'Select a Province'), ('Western Province', 'Western Province'), ('Southern Province', 'Southern Province'), ('Eastern Province', 'Eastern Province'), ('Central Province', 'Central Province'), ('Northcentral Province', 'Northcentral Province'), ('Northern Province', 'Northern Province'), ('Northwest Province', 'Northwest Province'), ('Uwa Province', 'Uwa Province')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='BulkOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=10, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('bulk_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomerAndSalesManagement.bulkorderrequest')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomerAndSalesManagement.salesproduct')),
            ],
        ),
    ]
