# Generated by Django 4.1.2 on 2022-11-03 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerAndSalesManagement', '0006_alter_order_date_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 18, 35, 25, 316573)),
        ),
    ]
