# Generated by Django 4.1.1 on 2022-09-22 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WarehouseManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(choices=[('Western Province', 'Western Province'), ('Southern Province', 'Southern Province'), ('Eastern Province', 'Eastern Province'), ('Central Province', 'Central Province'), ('Northcentral Province', 'Northcentral Province'), ('Northern Province', 'Northern Province'), ('Northwest Province', 'Northwest Province'), ('Uwa Province', 'Uwa Province')], max_length=200, null=True)),
                ('delivery_cost', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, null=True)),
                ('contact_number', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True)),
                ('LicenseNumber', models.CharField(max_length=100, null=True)),
                ('nic', models.CharField(max_length=100, null=True)),
                ('LicenseValid', models.CharField(choices=[('License Valid', 'License Valid'), ('License Expired', 'License Expired')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelVehicle', models.CharField(max_length=20, null=True)),
                ('make', models.CharField(max_length=20, null=True)),
                ('LicensePlate', models.CharField(max_length=50, null=True)),
                ('exteriorColor', models.CharField(max_length=20, null=True)),
                ('year', models.PositiveIntegerField(null=True)),
                ('transmission', models.CharField(max_length=20, null=True)),
                ('driveTrain', models.CharField(max_length=20, null=True)),
                ('fuelType', models.CharField(max_length=20, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('condition', models.CharField(choices=[('Need to be repaired', 'Need to be repaired'), ('Good condition', 'Good condition')], max_length=20, null=True)),
                ('BodyStyle', models.CharField(max_length=20, null=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DeliveryManagement.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderID', models.CharField(max_length=7, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('receivedDate', models.DateField(auto_now_add=True)),
                ('progress', models.CharField(choices=[('', 'Select a Status'), ('Received', 'Received'), ('Preparing', 'Preparing'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], default='Received', max_length=30, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseManagement.product')),
            ],
        ),
    ]
