# Generated by Django 4.1.2 on 2022-11-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='BodyStyle',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='driveTrain',
            new_name='engineCapacity',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='make',
            new_name='mileage',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='trim',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
