# Generated by Django 4.1.1 on 2022-09-22 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('contact_no', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('product_category', models.CharField(choices=[('Raw materials', 'Raw materials'), ('Packaging materials', 'Packaging materials'), ('Equipments', 'Equipments')], max_length=20)),
                ('username', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_ID', models.PositiveIntegerField(null=True)),
                ('itemName', models.CharField(max_length=20, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('due_Date', models.DateField(null=True)),
                ('Note', models.TextField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Re-ordered', 'Re-ordered'), ('Canceled', 'Canceled'), ('Paid', 'paid'), ('ordered', 'ordered'), ('toreturn', 'toreturn')], default='Pending', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=50, null=True)),
                ('Unit_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Unit', models.CharField(max_length=15, null=True)),
                ('Supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=70, null=True)),
                ('contact_no', models.CharField(max_length=20, null=True)),
                ('product_category', models.CharField(choices=[('Raw materials', 'Raw materials'), ('Packaging materials', 'Packaging materials'), ('Equipments', 'Equipments')], max_length=20)),
                ('profile_image', models.ImageField(default='avatar.png', upload_to='Profile_images')),
                ('account_no', models.PositiveIntegerField(blank=True, null=True)),
                ('bankWithBranch', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Returns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund', models.BooleanField(default=False, verbose_name='Refund')),
                ('Ship_again', models.BooleanField(default=False, verbose_name='Ship again')),
                ('Description', models.TextField(blank=True, null=True)),
                ('return_status', models.CharField(choices=[('pending', 'pending'), ('refunded', 'refunded'), ('re-shipped', 're-shipped')], default='pending', max_length=30, null=True)),
                ('request_ID', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='SupplierManagement.orderrequest')),
            ],
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='SupplierID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SupplierManagement.supplierinfo'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_image', models.ImageField(null=True, upload_to='s_orders/payslips/')),
                ('orderedDate', models.DateField(auto_now_add=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('further_details', models.TextField(blank=True, null=True)),
                ('viewed_status', models.CharField(choices=[('viewed', 'viewed'), ('new', 'new'), ('received', 'received')], default='new', max_length=30, null=True)),
                ('request_ID', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='SupplierManagement.orderrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_pdf', models.FileField(blank=True, null=True, upload_to='invoices/pdfs/')),
                ('invoice_image', models.ImageField(blank=True, null=True, upload_to='invoices/images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('request_ID', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='SupplierManagement.orderrequest')),
            ],
        ),
    ]
