# Generated by Django 4.1.2 on 2022-10-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending')], max_length=20, null=True),
        ),
    ]
